apiVersion: apps/v1
kind: Deployment
metadata:
  name: bysykkel
spec:
  selector:
    matchLabels:
      app: bysykkel-sampler
  template:
    metadata:
      labels:
        app: bysykkel-sampler
    spec:
      containers:
      - name: bysykkel
        imagePullPolicy: Always
        image: gcr.io/cognite-experiments/andershaf-bysykkel:latest
        env:
          - name: COGNITE_PROJECT
            value: andershaf
          - name: COGNITE_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: cognite_api_key
          - name: BYSYKKEL_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: bysykkel_api_key