apiVersion: v1
kind: Pod
metadata:
  name: bysykkel
spec:
  containers:
  - name: bysykkel
    image: gcr.io/cognite-experiments/andershaf-bysykkel:latest
    env:
      - name: COGNITE_API_KEY_AH
        valueFrom:
          secretKeyRef:
            name: api-keys
            key: cognite_apikey
      - name: BYSYKKEL_API_KEY
        valueFrom:
          secretKeyRef:
            name: api-keys
            key: bysykkelapi